### ISSUE TITLE
weather2 very slow if non-US postal is present

### ISSUE THREAD

**Issue by kwaaak** [dasu/syrup-sopel-modules#20]
Test cases:
.wf yyx
.wf y

The UV function needs to run only if the zip code is from the United States

**Comment by dasu** [comment]
Yeah I had a feeling it may give issues for international users.  Will fix it. (Actually thinking about revamping it and using Google maps for location data...I don't know...)

**Comment by dasu** [comment]
Actually what would you define as slow?  I had a user that was in Italy that was using .wf without any apparent slowness, and just did your two test cases and saw near instant results (heck it even seemed faster than a USA .wf).  Regardless the current script basically shows a None at the end of the string for international .wf, so i'll be making it skip that if the country is not USA.

**Comment by dasu** [comment]
Should be resolved with 7120aa2
