### ISSUE TITLE
weather2: Google short URL service will be shutting down

### ISSUE THREAD

**Issue by kwaaak** [dasu/syrup-sopel-modules#33]
> Starting May 30, 2018, only projects that have accessed URL Shortener APIs before today can create short links.

> If you are already calling URL Shortener APIs to manage goo.gl short links, you can continue to use them for a period of one year, until March 30, 2019, when we will discontinue the APIs.

https://developers.googleblog.com/2018/03/transitioning-google-url-shortener.html

**Comment by dasu** [comment]
Yup saw that, thanks!  FDLs look pretty lame `https://abc123.app.goo.gl/WXYZ`
bitly, owly are another option, but I hate signing up for stuff.  Wonder if there is an api-free URL shortener service. 
By the way, did you ever look into #30 review comments I left?

**Comment by kwaaak** [comment]
Yeah, I am not using the setlocation stuff so I haven't had the leisure to finish it up.

**Comment by dasu** [comment]
added bit.ly support with 30fd467 and fixed a mistake with the function in 9844b5ac
