### ISSUE TITLE
pb.py does not send message

### ISSUE THREAD

**Issue by Strykar** [dasu/syrup-sopel-modules#39]
pb.py merely prints the title of the url I'm attempting to send to $nick. I do not get a notification on  the PB app. I have the API in there, what am I missing?

**Comment by dasu** [comment]
Hmm a couple of things I can think of off the top of my head:
Have the pushbullet library installed: https://pypi.org/project/pushbullet.py/0.10.0/
Make sure you're replacing 'NICK_GOES_HERE', and of course your API key goes in 'API_KEY_GOES_HERE'

You can also try manually entering the PB portion in a python session to see if it works by itself.

**Comment by Strykar** [comment]
It was an issue with the nick, sorry. Thank you!
