### ISSUE TITLE
youtoob.py - [YouTube] Lookup failed: The request is missing a valid API key.

### ISSUE THREAD

**Issue by Strykar** [dasu/syrup-sopel-modules#41]
I've double checked the IP restrictions and even regenerated a new YT Data API key and updated sopel's conf, but I still get:
```
[YouTube] Lookup failed: The request is missing a valid API key.
[YouTube Search] The request is missing a valid API key.
```
To confirm it's not an API issue, https://github.com/sopel-irc/sopel-youtube works fine with the same API.
What am I missing here?

**Comment by dasu** [comment]
I have the API key hard-coded on this line, you just need to add yours.  You can also un-comment the code for that function to use the one in your config if you already have it set up.
https://github.com/dasu/syrup-sopel-modules/blob/master/youtoob.py#L76

**Comment by Strykar** [comment]
@dasu That fixed it, thank you!
IIRC, it would show the likes in green and dislikes in red in the past or am I confusing it with the sopel YT plugin?

**Comment by dasu** [comment]
Maybe that's the sopel YT plugin.  I personally don't like making things too colorful like that.
