### ISSUE TITLE
steam.py Unexpected error (Expecting value: line 1 column 1 (char 0))

### ISSUE THREAD

**Issue by Strykar** [dasu/syrup-sopel-modules#42]
Running .steam gives me
`Unexpected error (Expecting value: line 1 column 1 (char 0)) from Strykar at 2020-08-19 08:05:58.502673. Message was: .steam`

**Comment by dasu** [comment]
I didn't have the latest steam.py uploaded.  Try the new one.

**Comment by Strykar** [comment]
@dasu Cheers, closing!
