### ISSUE TITLE
weather2.py fails for some cities

### ISSUE THREAD

**Issue by Strykar** [dasu/syrup-sopel-modules#6]
We can reproduce the issue by checking weather for the city of Goa, it fails with:
`TypeError: 'NoneType' object has no attribute '__getitem__' (file "/usr/local/lib/python2.7/dist-packages/sopel/modules/weather.py", line 184, in weather)`

**Comment by dasu** [comment]
What state/county is this city from?

**Comment by Strykar** [comment]
Ah sorry, city does not exist, it's a state name, my mistake. Could we change the error to be descriptive like 'city not found' instead? Please close this.

**Comment by dasu** [comment]
Fixed it with https://github.com/dasu/syrup-willie-modules/commit/b6ea82de85bf39bf7325d48305e2d39f40e2533c
Hopefully it helps.
